name: Clone PR

runs:
  using: "composite"
  steps:
    - name: Parse Forgejo payload
      uses: ./.github/workflows/parse

    - name: Print env vars
      shell: bash
      run: |
        echo "Clone URL: $FORGEJO_CLONE_URL"
        echo "Number: $FORGEJO_NUMBER"
        echo "Ref: $FORGEJO_REF"
        echo "Repository: $FORGEJO_REPOSITORY"
        echo "Title: $FORGEJO_TITLE"

    - name: Checkout Repo
      shell: bash
      run: |
        git clone "$FORGEJO_CLONE_URL" test
        cd test
        git reset --hard $FORGEJO_REF
        git submodule update --init --recursive

        ls

    - name: Clone Eden (TMP)
      shell: bash
      run: |
        git clone https://git.eden-emu.dev/eden-emu/eden.git --recursive -b new-ci
