name: Get Variables

runs:
  using: "composite"
  steps:
    - name: Parse Forgejo payload
      shell: bash
      run: |
        PAYLOAD_JSON='${{ toJSON(github.event.client_payload) }}'
        echo "FORGEJO_CLONE_URL=$(echo "$PAYLOAD_JSON" | jq -r '.clone_url')" >> $GITHUB_ENV
        echo "FORGEJO_NUMBER=$(echo "$PAYLOAD_JSON" | jq -r '.number')" >> $GITHUB_ENV
        echo "FORGEJO_REF=$(echo "$PAYLOAD_JSON" | jq -r '.ref')" >> $GITHUB_ENV
        echo "FORGEJO_REPOSITORY=$(echo "$PAYLOAD_JSON" | jq -r '.repository')" >> $GITHUB_ENV
        echo "FORGEJO_TITLE=$(echo "$PAYLOAD_JSON" | jq -r '.title')" >> $GITHUB_ENV

    - name: Use environment variables
      shell: bash
      run: |
        echo "Clone URL: $FORGEJO_CLONE_URL"
        echo "Number: $FORGEJO_NUMBER"
        echo "Ref: $FORGEJO_REF"
        echo "Repository: $FORGEJO_REPOSITORY"
        echo "Title: $FORGEJO_TITLE"

    - name: Checkout Repo
      shell: bash
      run: |
        git clone "$FORGEJO_CLONE_URL" test
        cd test
        git reset --hard $FORGEJO_REF
        git submodule update --init --recursive

        ls
