name: Pull Request

on:
  repository_dispatch:
    types: [pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          chmod +x ./get-dependencies.sh
          ./get-dependencies.sh

      - name: Get Variables and Clone
        uses: ./.github/workflows/base

      - name: Get info
        shell: bash
        run: |
          echo "Clone URL: $FORGEJO_CLONE_URL"
          echo "Number: $FORGEJO_NUMBER"
          echo "Ref: $FORGEJO_REF"
          echo "Repository: $FORGEJO_REPOSITORY"
          echo "Title: $FORGEJO_TITLE"

      - name: Build
        shell: bash
        run: |
          cd eden
          TARGET=appimage DEVEL=true ./.ci/linux/build.sh v3

      - name: Package
        shell: bash
        run: |
          cd eden
          DEVEL=true ./.ci/linux/package.sh v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: linux
          path: eden/*.AppImage*
